# Increase minimum buffer quantum to prevent audio crackling during high CPU load
context.properties = {
    default.clock.quantum     = 1024
    default.clock.min-quantum = 1024
    default.clock.max-quantum = 2048
}
