-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:AU Optronics 0x243D",
  mode = "1920x1080@60.031",
  position = "0x0",
  scale = 1.2,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
